name: fastbook
channels:
    - fastai
    - pytorch
    - defaults
dependencies:
  - python>=3.6
  - pytorch>=1.6
  - torchvision
  - pip
  - pip:
    - fastai>=2.0.0
    - numpy==1.21.0
    - graphviz
    - ipywidgets
    - matplotlib
    - nbdev>=0.2.12
    - pandas
    - scikit_learn
    - azure-cognitiveservices-search-imagesearch
    - sentencepiece
    - streamlit
